name = "manga-radar-api"
main = "src/index.ts"
compatibility_date = "2025-03-17"

# 每天凌晨 3 點（UTC，台灣 11 點）清理舊資料
[triggers]
crons = ["0 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "manga-radar-db"
database_id = "8210aa36-5726-4309-bc72-a8ad278486c5"
